plugins:
  postcss-import: {}

  postcss-extend: {} # DEPRECATED

  postcss-mixins: {}

  '@csstools/postcss-design-tokens': {}

  postcss-preset-env:
    # https://github.com/csstools/postcss-plugins/tree/main/plugin-packs/postcss-preset-env#stage
    stage: false

    # https://github.com/csstools/postcss-plugins/blob/main/plugin-packs/postcss-preset-env/FEATURES.md
    features:
      custom-media-queries: true
      media-query-ranges: true
      nesting-rules: true
      custom-selectors: true
      relative-color-syntax: true
      # This feature (to come in v8) is not ready yet
      # https://github.com/csstools/postcss-plugins/issues/481#issuecomment-1335678359
      cascade-layers: false

  cssnano:
    # https://github.com/cssnano/cssnano/tree/cssnano%405.1.15/packages/cssnano-preset-default
    preset:
      - 'default'
      - # Both of these are disabled to allow manual CSS build tests
        # The `discardDuplicates` is disabled to prevent hiding duplicate CSS
        discardDuplicates: false
        mergeRules: false
        # So that if we use `initial` it remains `initial`
        # SEE: src/lib/_imports/tools/x-mailto-text-replace.css
        reduceInitial: false

  postcss-banner:
    banner: 'no build id'
    inline: true
    important: true

  postcss-replace:
    # @tacc/core-styles 'demo/' expects `./fonts`, but src uses `../../fonts`
    pattern: ../../fonts/
    data:
      # FAQ: Do not prepend './', cuz downstream postcss-import will strip it
      # FAQ: A string matching any final output simplifies downstream testing
      replaceAll: fonts/
